services:
  hoppscotch-aio:
        container_name: hoppscotch-aio
        restart: always
        image: hoppscotch/hoppscotch
        env_file:
            - ./.env
        environment:
            - DATABASE_URL=postgresql://postgres:xxxx@hoppscotch-db:5432/hoppscotch?connect_timeout=300
        depends_on:
            hoppscotch-db:
                condition: service_healthy
        ports:
            - "5000:5000"
        command: >
            sh -c "pnpx prisma migrate deploy && node /usr/src/app/aio_run.mjs"
  hoppscotch-db:
        image: postgres:15
        container_name: hoppscotch-db
        restart: always
        user: postgres
        environment:
            # PostgreSQL default user and credentials
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: xxxx
            POSTGRES_DB: hoppscotch
        healthcheck:
            test:
                [
                "CMD-SHELL",
                "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
                ]
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - hoppscotch-db:/var/lib/postgresql/data

volumes:
  hoppscotch-db:
